### PR TITLE
Provide utility to convert method names to MUBench format

### PR DESCRIPTION
**Pull request by M8is**
Implement #240: Provide utility to convert method names to MUBench format.

Took the MuBenchMethodFormatConverter from the FindBugs project on Bitbucket. Since the JVM representation doesn't contain the additional information, we need to pass things like the declaring type name, and method name manually.

### CODE REVIEW

**Comment by salsolatragus** [comment]
Check whether the utils work for the following detector runners:

* [ ] DMMC
* [ ] Jadet/Tikanga

**Comment by salsolatragus** [comment]
What's the state of this? Can I support this?

**Comment by M8is** [comment]
Currently, I checked for compatibility with Jadet and Tikanga. It seems to work well for these, but I noticed that my naming of `SourceCodeMethodIdentifier` is probably way off there. @salsolatragus You could suggest another name.
I noticed that DMMC uses yet another format, but it since the conversion is basically already implemented there, it shouldn't be a problem to reuse that code for a `MethodIdentifier` implementation. I can probably do that before thursday.

**Comment by salsolatragus** [comment]
`DMMC` is using plain Bytecode representation, as far as I remember, doesn't it? Didn't you implement that already? `JVMMethodIdentifier` or `BytecodeMethodIdentifier` would be options then.

The usage representation of Jadet and Tikanga is called OUM (Object Usage Model). If the implementation is indeed specific to these two detectors, we could call it `OUMMethodIdentifier`?

I remember that I thought we could have a more general identifier that happens to also properly handle OUM identifiers... might have been wrong though. If the implementations are indeed specific to certain detectors, I would agree to place them in the runners, even though we then still have duplication between Jadet and Tikanga. At least the `JVMMethodIdentifier` should be in `cli` though, since it's independent of a concrete detector.

**Comment by M8is** [comment]
`DMMC` uses `ObjectTrace` instances, which contain a `location` (the class as a FQN) and a context (the method signature). If we combine these, we should be able to reuse the `OUMMethodIdentifier` used for `Jadet` and `Tikanga`. 
I've implemented this in `DMMCMethodIdentifier`, so you can take a look. I'd argue that it would be best if `DMMCMethodIdentifier` could use `ObjectTrace` directly, so I'd probably move it into `DMMC`.

**Comment by M8is** [comment]
About where to put the `MethodIdentifier` implementations before we do that: I think `OUMMethodIdentifier` and `JVMMethodIdentifier` are fine, and with the `DMMCMethodIdentifier` out, we'd be clean.

What's left to do is to release the `mubench.cli` changes so we can officially use these identifiers in the detectors.

**Comment by salsolatragus** [comment]
Yes, we need to release. Can do this on Thursday.

I agree with your placement of the classes, but I'm now again unhappy with the `OUM` name, because `DMMC` does not use OUM... the question is, what is it then?

**Comment by M8is** [comment]
`Jadet`, `Tikanga`, and `DMMC` now use the new util.

**Comment by salsolatragus** [comment]
Ok, this means I can merge this PR and finally work on closing #239, right?

**Pull request merged**
